### PR TITLE
Use deploy directive instead of after_success

### PR DESCRIPTION
**Pull request by tanakahisateru**
**AN EXPERIMENTAL PR**

I prefer to use deploy directive but I'm not sure which this change correctly works or not.
https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A

Now deploy.sh may be too danger because it can break git repo everywhere.

### CODE REVIEW

**Comment by tanakahisateru** [comment]
`$ bash ./.bin/deploy.sh` disappeared from this build.

**Comment by featherplain** [comment]
@tanakahisateru 
Thank you! Sorry to late for reply.
May be this way is better.

> Now deploy.sh may be too danger because it can break git repo everywhere.

I'm not sure why it's too danger, which case do you think to happen?

**Comment by tanakahisateru** [comment]
@featherplain `.bin/deploy.sh` can run anywhere even if out of Travis... ?? Ah :scream_cat: ... there is no blocking conditions also before this change. OK, no problem here.

日本語でもOKですか。 `.bin/deploy.sh` は手元のファイルを壊してgithubにpushしてしまうのでTravis以外でもさくっと実行できてしまうようになって危ない、とおもったんですが、よく見たらそれ以前でもTravis以外で停止するような条件なかったので、これとは関係ない問題ですね。

**Comment by featherplain** [comment]
@tanakahisateru 
なるほど、ありがとうございます(そしてリプライ遅くてすみません)。マージします!

**Pull request merged**
